name: root
channels:
  - defaults
  - bioconda
  - conda-forge
#  - biobuilds
dependencies:
  - biopython
  - matplotlib
  - numpy
  - python=3.9
  - snakemake-minimal
  - bwa=0.7.12
  - samtools
#  - bedtools
#  - ivar>=1.3.1
#  - nextalign
#  - mafft
#  - mash